import Head from 'next/head'
import Image from 'next/image'
import formImage from '../public/blink.png'
import { Inter } from '@next/font/google'
import { useFormik } from 'formik'
import * as Yup from 'yup'
import { useRouter } from 'next/router'
import { motion as m } from "framer-motion"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  //Router
 const router = useRouter();


  
  //Formik Logic
  const formik = useFormik({
    initialValues: {
      enquiry: 'Incorrect Pay',
      date: '',
      query: '',
    },

    validationSchema: Yup.object({    
      date: Yup.date().default(() => new Date()),
    
      query: Yup.string().required('Required')
      ,
    }),
 
    //submit form
  onSubmit: (values) => {
    console.log(values)
    router.push({ pathname: '/success', query: values})
  }
  })

console.log(formik.errors)
  
  return (
    <m.div
    initial={{ opacity: 0 }}
    animate={{ opacity: 1 }}
    exit={{ opacity: 0 }}
    className="absolute w-full"
    >
      <Head>
        <title>Blink Payroll Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/blink.ico" />
      </Head>
      
      <main className='h-screen flex items-center justify-center'>
       <form 
        onSubmit={formik.handleSubmit}
        className='bg-white flex rounded-lg w-1/2 font-latoBold'>
         <div className='flex-1 text-gray-700 p-20'>
          <h1 className='text-3xnt-latoBold'>
             Payroll Enquriy
             </h1>
             <br>
             </br>
          <p> 
            Enquire today about our payroll services and we will get back to you as soon as possible.
          </p>
            <br>
            </br>
            {/*Enquiry dropdown */}
            <div>
              <div className="pb-4">
                <label
                  htmlFor="enquiry"
                  className="block font-latoBold text-sm pb-2"
                >
                  WHAT DOES YOUR ENQUIRY RELATE TO?
                </label>
                <select
                  className="border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500"
                  name="enquiry"
                  value={formik.values.enquiry}
                  onChange={formik.handleChange}
                >
                  <option>Incorrect Pay</option>
                  <option>Missing Expense</option>
                  <option>Change of Bank Details</option>
                  <option>Change of Address</option>
                  <option>Other</option>
                </select>
                {/*Enquiry date */}
                <div>
                  <div className='pb-4'>
                    <lablel
                     htmlFor="date"
                     className= "block font-latoBold text-sm pb-2"
                     >
                        DATE OF ENQUIRY (IF KNOWN)
                    </lablel>
                    <input
                    className='border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500'
                    type="date"
                    name="date"
                    placeholder="DD/MM/YYYY"
                    value={formik.values.date}
                    onChange={formik.handleChange}
                    />
                  </div>
                  {/*Query */}
                  <div>
                    <div className='pb-4'>
                      <lablel
                       htmlFor="query"
                        className= {"block font-latoBold text-sm pb-2 ${formiks.errors.query ? 'text-red-400' : ' '}"}                        
                       >
                        {formik.errors.query ? formik.errors.query : 'PLEASE ENTER'}
                      </lablel>
                      <input
                      className='border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500'
                      type="text"
                      name="query"
                      placeholder="Please enter your query"
                      value={formik.values.query}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      />
                    </div>
                  </div>
                  <button type="submit"
                   className='bg-teal-500 font-latoBold text-sm text-white py-3 mt-6 rounded-lg w-full' >Submit </button>
                </div>
            </div>
          </div>
         </div>
         <div className='relative flex-1'>
          <Image alt='form-learn' src={formImage} fill className='object-cover rounded-lg'/>
          </div>         
       </form>
      </main>
      
      
      
      </m.div>
    
  )
}
